### PR TITLE
Use use-sync-external-store shim so that react-yjs is backwards compatible

### PR DESCRIPTION
**Pull request by Laura**
Uses shim so that the library would work with versions of react before 18 :)

### CODE REVIEW

**Comment by nikgraf** [comment]
hey @Laura, thanks for the PR!

I think since the library is quite new and we never supported older React versions I would not add this kind of support. Better to require React 18 with this one and maybe you could publish a fork to support older versions

**Comment by Laura** [comment]
Np. Out of curiosity, are you planning on adding more functionality to the library that might require React 18?

**Comment by nikgraf** [comment]
@Laura not sure - I think the next thing that could/would be valuable is a hook for y-awarness

btw I'm open for suggestions! Any pain points with Yjs you would like to be solved?

**Comment by Laura** [comment]
I ended up using y-presence for my presence stuff, but presence would be super helpful! :)

**Comment by nikgraf** [comment]
great, will look into it. closing the PR for now

**Pull request closed without merging**
